version: "3.9"
    
services:
  app_occu_notify:
    build:
      context: .

  crate01:
    image: crate
    hostname: crate01
    ports:
      - "4201:4200"
    environment:
      CRATE_HEAP_SIZE: 1g
    command: crate -Cnetwork.host=_site_ -Cdiscovery.type=single-node
